FROM node:24-slim

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

RUN apt update \
    && apt install --assume-yes --no-install-recommends \
        build-essential \
        python3

WORKDIR /apps/crud-dapp

COPY ./package.json ./
COPY ./pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .
CMD [ "pnpm", "run", "dev" ]