import './globals.css';
import { UiLayout } from '@/components/ui/ui-layout';
import { ReactQueryProvider } from './react-query-provider';

export const metadata = {
  title: 'Gametokenpool',
  description: 'Generated by create-solana-dapp',
};

const links: { label: string; path: string }[] = [
  { label: 'Admin', path: '/admin' },
  { label: 'Game', path: '/game' },
  // { label: 'Game Wallet', path: '/game-wallet' },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <ReactQueryProvider>
          <UiLayout links={links}>{children}</UiLayout>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
