[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
gametokenpool = "3eVNw2R4rSaPew9D5SDJRL1roF4fV4EgJe1W5EMvAGNm"

[programs.devnet]
gametokenpool = "3eVNw2R4rSaPew9D5SDJRL1roF4fV4EgJe1W5EMvAGNm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./tests/fixtures/keys/program-owner.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
